### PR TITLE
Add new ibeji-example-applications repo

### PR DESCRIPTION
**Pull request by wilyle**
Add new ibeji-example-applications repo. This repo will hold some samples and integrations with other SDV components

### CODE REVIEW

**Comment by netomi** [comment]
Can we get an approval from a project lead or second committer?

**Review by ashbeitz — APPROVED** [review]
Approved.

**Comment by ashbeitz** [comment]
@eclipsefdn-security @eclipsefdn-releng - Can you please review?

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created.

**Pull request merged**
